[package]
name = "raven-game-editor"
version = "0.1.0"
edition = "2024"
description = "Asset editor for games running in the Raspberry Pi Pico"
license = "MIT"
keywords = ["gamedev"]

[dependencies]
eframe = "0.36.1"
egui = "0.36.1"
egui_extras = { version = "0.36.1", features = ["all_loaders"] }
image = { version = "0.25", features = ["png"] }
regex = "1.12.4"
rfd = "0.17.2"
time = { version = "0.3.53", features = ["formatting", "local-offset"] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
soloud = { version = "1.1.1", optional = true }
cpal = { version = "0.18.1", optional = true }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
log = "0.4.33"
serde = { version = "1.0.229", features = ["derive"] }
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3.104", features = ["Storage", "Window", "Document", "HtmlElement", "Text"] }

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2

[features]
default = ["cpal_sound"]
soloud_sound = ["dep:soloud"]
cpal_sound = ["dep:cpal"]
no_sound = []

[build-dependencies]
time = { version = "0.3.53", features = ["formatting", "local-offset"] }
