mod ident_store;
mod map_data;
mod sprite_animation;
mod tile_animation;
mod room;
mod font;
mod prop_font;
mod pal_sprite;
mod mod_data;
mod sfx;
mod tileset;
mod sprite;
mod world;

use std::cell::RefCell;
use std::io::Result;
use std::sync::LazyLock;

use ident_store::{*};

use super::{
    StringLogger,
    DataAssetStore,
    DataAssetId,
    DataAssetType,
    DataAsset,
    AssetIdList,
};

static HUMAN_TIMESTAMP_FORMAT: LazyLock<time::format_description::FormatDescriptionV3> = LazyLock::new(
    || time::format_description::parse_borrowed::<3>("[year]-[month]-[day] [hour]:[minute]:[second]").unwrap());
static MACHINE_TIMESTAMP_FORMAT: LazyLock<time::format_description::FormatDescriptionV3> = LazyLock::new(
    || time::format_description::parse_borrowed::<3>("[year][month][day]00[hour][minute][second]").unwrap());

struct ProjectDataWriter<'a> {
    output: RefCell<String>,
    logger: RefCell<&'a mut StringLogger>,
    store: &'a DataAssetStore,
    ident: IdentStore,
}

impl<'a> ProjectDataWriter<'a> {
    pub fn new(store: &'a DataAssetStore, logger: &'a mut StringLogger) -> Self {
        ProjectDataWriter {
            output: RefCell::new(String::new()),
            logger: RefCell::new(logger),
            store,
            ident: IdentStore::new(&store.project_prefix),
        }
    }

    fn write<S: AsRef<str>>(&self, data: S) {
        self.output.borrow_mut().push_str(data.as_ref());
    }

    fn log<S: AsRef<str>>(&self, msg: S) {
        self.logger.borrow_mut().log(msg);
    }

    fn write_header(&self) -> Result<()> {
        let timestamp = if cfg!(target_arch = "wasm32") {
            self.write("// Auto-generated by raven-game-editor [wasm]\n");
            None
        } else {
            let local_time = time::OffsetDateTime::now_local();

            if let Ok(now) = local_time && let Ok(formatted_date) = now.format(&HUMAN_TIMESTAMP_FORMAT) {
                self.write(format!("// Auto-generated at {} by raven-game-editor\n", formatted_date));
            } else {
                self.write("// Auto-generated by raven-game-editor\n");
                self.log("WARNING: couldn't format current datetime for comment");
            }

            if let Ok(now) = local_time && let Ok(formatted_date) = now.format(&MACHINE_TIMESTAMP_FORMAT) {
                Some(formatted_date)
            } else {
                None
            }
        };

        self.write("\n");
        self.write(format!("#define {}_DATA_FILE_VERSION {}\n", self.ident.prefix_upper, DataAssetStore::VERSION));
        self.write("\n");
        self.write(format!("#define {}_DATA_VGA_BITS_PER_PIXEL {}\n", self.ident.prefix_upper, self.store.vga_bits_per_pixel));
        self.write(format!("#define {}_DATA_VGA_SYNC_BITS {:#04x}\n", self.ident.prefix_upper, self.store.vga_sync_bits));
        self.write(format!("#define {}_DATA_TILES_PER_WORLD_BLOCK {}\n", self.ident.prefix_upper, self.store.tiles_per_world_block));

        if let Some(timestamp) = timestamp {
            self.write(format!("#define {}_DATA_SAVE_TIMESTAMP 0x{}\n", self.ident.prefix_upper, timestamp));
        } else {
            self.write(format!("#define {}_DATA_SAVE_TIMESTAMP 0\n", self.ident.prefix_upper));
            self.log("WARNING: couldn't format current datetime for SAVE_TIMESTAMP #define");
        }

        self.write("\n");
        self.write(format!("#if {}_DATA_BYTES\n", self.ident.prefix_upper));
        self.write("\n");
        Ok(())
    }

    fn write_data_end(&self) -> Result<()> {
        self.write(format!("#endif /* {}_DATA_BYTES */\n", self.ident.prefix_upper));
        self.write("\n");
        Ok(())
    }

    fn write_footer(&self, merge_sample_saved_size: usize) -> Result<()> {
        let total_size = self.store.assets.data_size() - merge_sample_saved_size;
        self.write(format!("// total data size: {} bytes\n", total_size));
        self.log(format!("-> TOTAL data size: {} bytes ({} saved by sample merging)", total_size, merge_sample_saved_size));
        Ok(())
    }

    fn pixel_to_6bpp(&self, pixel: u8) -> u8 {
        let r6 = (pixel >> 1) & 0x3;
        let g6 = (pixel >> 4) & 0x3;
        let b6 = (pixel >> 6) & 0x3;
        let pix6 = r6 | (g6 << 2) | (b6 << 4);
        (pix6 & 0x3f) | self.store.vga_sync_bits
    }

    fn copy_image_row(dest: &mut [u8], src: &[u8], mirror: bool) {
        if mirror {
            for (d, s) in dest.iter_mut().zip(src.iter().rev()) {
                *d = *s;
            }
        } else {
            for (d, s) in dest.iter_mut().zip(src.iter()) {
                *d = *s;
            }
        }
    }

    fn write_image_item_6bits(&self, width: u32, height: u32, item_num: u32, pixels: &[u8], mirror: bool) {
        let empty_pixel = self.store.vga_sync_bits as u32;
        let empty_quad = empty_pixel | empty_pixel << 8 | empty_pixel << 16 | empty_pixel << 24;
        let width = width as usize;
        let height = height as usize;
        let item_num = item_num as usize;
        let stride = width.div_ceil(4);
        let mut image_row = vec![self.store.vga_sync_bits; width];
        for y in 0..height {
            let index = (item_num * height + y) * width;
            Self::copy_image_row(&mut image_row, &pixels[index..index+width], mirror);
            for s in 0..stride {
                if s.is_multiple_of(8) { self.write("\n  "); }
                let mut quad = empty_quad | (self.pixel_to_6bpp(image_row[s*4]) as u32);
                if width > s*4+1 { quad |= (self.pixel_to_6bpp(image_row[s*4 + 1]) as u32) <<  8; }
                if width > s*4+2 { quad |= (self.pixel_to_6bpp(image_row[s*4 + 2]) as u32) << 16; }
                if width > s*4+3 { quad |= (self.pixel_to_6bpp(image_row[s*4 + 3]) as u32) << 24; }
                self.write(format!("{:#10x},", quad));
            }
        }
        self.write("\n");
    }

    fn write_image_item_8bits(&self, width: u32, height: u32, item_num: u32, pixels: &[u8], mirror: bool) {
        let width = width as usize;
        let height = height as usize;
        let item_num = item_num as usize;
        let stride = width.div_ceil(4);
        let mut image_row = vec![self.store.vga_sync_bits; width];
        for y in 0..height {
            let index = (item_num * height + y) * width;
            Self::copy_image_row(&mut image_row, &pixels[index..index+width], mirror);
            for s in 0..stride {
                if s.is_multiple_of(8) { self.write("\n  "); }
                let mut quad = image_row[s*4] as u32;
                if width > s*4+1 { quad |= (image_row[s*4 + 1] as u32) <<  8; }
                if width > s*4+2 { quad |= (image_row[s*4 + 2] as u32) << 16; }
                if width > s*4+3 { quad |= (image_row[s*4 + 3] as u32) << 24; }
                self.write(format!("{:#10x},", quad));
            }
        }
        self.write("\n");
    }

    fn write_image_item(&self, width: u32, height: u32, item_num: u32, pixels: &[u8], mirror: bool) {
        if self.store.vga_bits_per_pixel == 8 {
            self.write_image_item_8bits(width, height, item_num, pixels, mirror);
        } else {
            self.write_image_item_6bits(width, height, item_num, pixels, mirror);
        }
    }

    // =========================================================================
    // === ASSET IDS
    // =========================================================================

    fn write_asset_ids_for(&self, asset_ids: &AssetIdList, asset_type: DataAssetType, type_name: &str) -> Result<()> {
        self.write(format!("enum {}_{}_IDS {{\n", self.ident.prefix_upper, type_name));
        for id in asset_ids.iter() {
            let name_id = self.ident.get_asset_name_id(asset_type, *id)?;
            let name_id_upper = name_id.to_ascii_uppercase();
            self.write(format!("  {}_{}_ID_{},\n", self.ident.prefix_upper, type_name, name_id_upper));
        }
        self.write(format!("  {}_{}_COUNT,\n", self.ident.prefix_upper, type_name));

        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_asset_ids(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === IDS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        self.write_asset_ids_for(&self.store.asset_ids.fonts, DataAssetType::Font, "FONT")?;
        self.write_asset_ids_for(&self.store.asset_ids.prop_fonts, DataAssetType::PropFont, "PROP_FONT")?;
        self.write_asset_ids_for(&self.store.asset_ids.mods, DataAssetType::ModData, "MOD")?;
        self.write_asset_ids_for(&self.store.asset_ids.sfxs, DataAssetType::Sfx, "SFX")?;
        self.write_asset_ids_for(&self.store.asset_ids.tilesets, DataAssetType::Tileset, "TILESET")?;
        self.write_asset_ids_for(&self.store.asset_ids.sprites, DataAssetType::Sprite, "SPRITE")?;
        self.write_asset_ids_for(&self.store.asset_ids.pal_sprites, DataAssetType::PalSprite, "PAL_SPRITE")?;
        self.write_asset_ids_for(&self.store.asset_ids.maps, DataAssetType::MapData, "MAP")?;
        self.write_asset_ids_for(&self.store.asset_ids.animations, DataAssetType::SpriteAnimation, "SPRITE_ANIMATION")?;
        self.write_asset_ids_for(&self.store.asset_ids.rooms, DataAssetType::Room, "ROOM")?;
        self.write_asset_ids_for(&self.store.asset_ids.worlds, DataAssetType::World, "WORLD")?;
        self.write_asset_ids_for(&self.store.asset_ids.tile_anims, DataAssetType::TileAnimation, "TILE_ANIMATION")?;

        Ok(())
    }

    // =========================================================================
    // === IMAGE SIZES
    // =========================================================================

    fn write_sprite_sizes(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === SPRITE SIZES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        let mult_mirrors = if super::Sprite::MIRROR_FRAMES { 2 } else { 1 };
        for id in self.store.asset_ids.sprites.iter() {
            if let Some(sprite) = self.store.assets.sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Sprite, *id)?;
                let name_id_upper = name_id.to_ascii_uppercase();
                self.write(format!("#define {}_SPRITE_WIDTH_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.width));
                self.write(format!("#define {}_SPRITE_HEIGHT_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.height));
                self.write(format!("#define {}_SPRITE_STRIDE_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.width.div_ceil(4)));
                self.write(format!("#define {}_SPRITE_FRAMES_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.num_frames*mult_mirrors));
                self.write("\n");
            }
        }

        for id in self.store.asset_ids.pal_sprites.iter() {
            if let Some(pal_sprite) = self.store.assets.pal_sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::PalSprite, *id)?;
                let name_id_upper = name_id.to_ascii_uppercase();
                self.write(format!("#define {}_PAL_SPRITE_WIDTH_{} {}\n", self.ident.prefix_upper, name_id_upper, pal_sprite.width));
                self.write(format!("#define {}_PAL_SPRITE_HEIGHT_{} {}\n", self.ident.prefix_upper, name_id_upper, pal_sprite.height));
                self.write(format!("#define {}_PAL_SPRITE_FRAMES_{} {}\n", self.ident.prefix_upper, name_id_upper, pal_sprite.num_frames));
                self.write(format!("#define {}_PAL_SPRITE_DEPTH_{} {}\n", self.ident.prefix_upper, name_id_upper,
                                   pal_sprite.depth.bits_per_pixel()));
                self.write("\n");
            }
        }
        Ok(())
    }

    // =========================================================================
    // === PROJECT
    // =========================================================================

    fn gen_unique_asset_names(&mut self) -> Result<()> {
        self.ident.add_assets(DataAssetType::Tileset, self.store);
        self.ident.add_assets(DataAssetType::MapData, self.store);
        self.ident.add_assets(DataAssetType::Room, self.store);
        self.ident.add_assets(DataAssetType::World, self.store);
        self.ident.add_assets(DataAssetType::Sprite, self.store);
        self.ident.add_assets(DataAssetType::PalSprite, self.store);
        self.ident.add_assets(DataAssetType::SpriteAnimation, self.store);
        self.ident.add_assets(DataAssetType::TileAnimation, self.store);
        self.ident.add_assets(DataAssetType::Sfx, self.store);
        self.ident.add_assets(DataAssetType::ModData, self.store);
        self.ident.add_assets(DataAssetType::Font, self.store);
        self.ident.add_assets(DataAssetType::PropFont, self.store);
        Ok(())
    }

    fn serialize(mut self) -> Result<String> {
        self.gen_unique_asset_names()?;
        self.write_header()?;

        font::write_fonts(&self, &self.store.asset_ids.fonts.store)?;
        prop_font::write_prop_fonts(&self, &self.store.asset_ids.prop_fonts.store)?;
        pal_sprite::write_pal_sprites(&self, &self.store.asset_ids.pal_sprites.store)?;
        let merge_sample_saved_size = mod_data::write_mods(&self, &self.store.asset_ids.mods.store)?;
        sfx::write_sfxs(&self, &self.store.asset_ids.sfxs.store)?;
        tileset::write_tilesets(&self, &self.store.asset_ids.tilesets.store)?;
        sprite::write_sprites(&self, &self.store.asset_ids.sprites.store)?;
        map_data::write_maps(&self, &self.store.asset_ids.maps.store)?;
        let anim_info = sprite_animation::write_sprite_animations(&self, &self.store.asset_ids.animations.store)?;
        tile_animation::write_tile_animations(&self, &self.store.asset_ids.tile_anims.store)?;
        room::write_rooms(&self, &self.store.asset_ids.rooms.store)?;
        world::write_worlds(&self, &self.store.asset_ids.worlds.store)?;

        room::write_scripts(&self, &self.store.asset_ids.rooms.store)?;

        self.write_data_end()?;

        sprite_animation::write_animation_names(&self, &self.store.asset_ids.animations.store, anim_info)?;
        room::write_room_item_names(&self, &self.store.asset_ids.rooms.store)?;
        world::write_world_item_names(&self, &self.store.asset_ids.worlds.store)?;
        self.write_asset_ids()?;
        self.write_sprite_sizes()?;

        self.write_footer(merge_sample_saved_size)?;
        Ok(self.output.take())
    }
}

pub fn serialize_project(store: &DataAssetStore, logger: &mut StringLogger) -> Result<String> {
    ProjectDataWriter::new(store, logger).serialize()
}

pub fn serialize_map(map_id: DataAssetId, store: &DataAssetStore, logger: &mut StringLogger) -> Result<String> {
    let mut writer = ProjectDataWriter::new(store, logger);
    writer.gen_unique_asset_names()?;
    writer.write_header()?;
    map_data::write_maps(&writer, &[map_id])?;
    writer.write_data_end()?;
    Ok(writer.output.take())
}

pub fn serialize_room(room_id: DataAssetId, store: &DataAssetStore, logger: &mut StringLogger) -> Result<String> {
    let mut writer = ProjectDataWriter::new(store, logger);
    writer.gen_unique_asset_names()?;
    writer.write_header()?;
    room::write_rooms(&writer, &[room_id])?;
    room::write_scripts(&writer, &[room_id])?;
    writer.write_data_end()?;
    room::write_room_item_names(&writer, &[room_id])?;
    Ok(writer.output.take())
}

pub fn serialize_sprite_animation(animation_id: DataAssetId, store: &DataAssetStore, logger: &mut StringLogger) -> Result<String> {
    let mut writer = ProjectDataWriter::new(store, logger);
    writer.gen_unique_asset_names()?;
    writer.write_header()?;
    let info = sprite_animation::write_sprite_animations(&writer, &[animation_id])?;
    writer.write_data_end()?;
    sprite_animation::write_animation_names(&writer, &[animation_id], info)?;
    Ok(writer.output.take())
}
