mod ident_store;

use std::fs;
use std::cell::RefCell;
use std::io::{Write, Result, Error};
use std::path::Path;
use std::collections::HashMap;
use regex::Regex;
use std::sync::LazyLock;

use ident_store::{*};

use super::{
    StringLogger,
    DataAssetStore,
    DataAssetId,
    DataAssetType,
    DataAsset,
    AssetIdList,
    RoomTriggerType,
};

static RE_UNNAMED_LOOP: LazyLock<Regex> = LazyLock::new(
    || Regex::new(r"^loop_[0-9]+$").unwrap());

static HUMAN_TIMESTAMP_FORMAT: LazyLock<time::format_description::FormatDescriptionV3> = LazyLock::new(
    || time::format_description::parse_borrowed::<3>("[year]-[month]-[day] [hour]:[minute]:[second]").unwrap());
static MACHINE_TIMESTAMP_FORMAT: LazyLock<time::format_description::FormatDescriptionV3> = LazyLock::new(
    || time::format_description::parse_borrowed::<3>("[year][month][day]00[hour][minute][second]").unwrap());

struct ModSampleRef {
    mod_id: DataAssetId,
    sample_index: usize,
}

struct AnimationInfo {
    add_foot: bool,
    loop_offsets: Vec<usize>,
    loop_index_to_name_id: HashMap<usize,String>,
}

pub struct ProjectDataWriter<'a> {
    output: RefCell<String>,
    logger: RefCell<&'a mut StringLogger>,
    store: &'a DataAssetStore,
    ident: IdentStore,
    animation_info: HashMap<DataAssetId, AnimationInfo>,
    merge_sample_saved_size: usize,
}

impl<'a> ProjectDataWriter<'a> {
    pub fn new(store: &'a DataAssetStore, logger: &'a mut StringLogger) -> Self {
        ProjectDataWriter {
            output: RefCell::new(String::new()),
            logger: RefCell::new(logger),
            store,
            ident: IdentStore::new(&store.project_prefix),
            animation_info: HashMap::new(),
            merge_sample_saved_size: 0,
        }
    }

    fn write<S: AsRef<str>>(&self, data: S) {
        self.output.borrow_mut().push_str(data.as_ref());
    }

    fn log<S: AsRef<str>>(&self, msg: S) {
        self.logger.borrow_mut().log(msg);
    }

    fn write_header(&self) -> Result<()> {
        let local_time = time::OffsetDateTime::now_local();

        if let Ok(now) = local_time && let Ok(formatted_date) = now.format(&HUMAN_TIMESTAMP_FORMAT) {
            self.write(format!("// Auto-generated at {} by raven-game-editor\n", formatted_date));
        } else {
            self.write("// Auto-generated by raven-game-editor\n");
            self.log("WARNING: couldn't format current datetime for comment");
        }

        self.write("\n");
        self.write(format!("#define {}_DATA_FILE_VERSION {}\n", self.ident.prefix_upper, DataAssetStore::VERSION));
        self.write("\n");
        self.write(format!("#define {}_DATA_VGA_BITS_PER_PIXEL {}\n", self.ident.prefix_upper, self.store.vga_bits_per_pixel));
        self.write(format!("#define {}_DATA_VGA_SYNC_BITS {:#04x}\n", self.ident.prefix_upper, self.store.vga_sync_bits));

        if let Ok(now) = local_time && let Ok(formatted_date) = now.format(&MACHINE_TIMESTAMP_FORMAT) {
            self.write(format!("#define {}_DATA_SAVE_TIMESTAMP 0x{}\n", self.ident.prefix_upper, formatted_date));
        } else {
            self.write(format!("#define {}_DATA_SAVE_TIMESTAMP 0\n", self.ident.prefix_upper));
            self.log("WARNING: couldn't format current datetime for SAVE_TIMESTAMP #define");
        }

        self.write("\n");
        self.write(format!("#if {}_DATA_BYTES\n", self.ident.prefix_upper));
        self.write("\n");
        Ok(())
    }

    fn write_data_end(&self) -> Result<()> {
        self.write(format!("#endif /* {}_DATA_BYTES */\n", self.ident.prefix_upper));
        self.write("\n");
        Ok(())
    }

    fn write_footer(&self) -> Result<()> {
        let total_size = self.store.assets.data_size() - self.merge_sample_saved_size;
        self.write(format!("// total data size: {} bytes\n", total_size));
        self.log(format!("-> TOTAL data size: {} bytes ({} saved by sample merging)", total_size, self.merge_sample_saved_size));
        Ok(())
    }

    fn pixel_to_6bpp(&self, pixel: u8) -> u8 {
        let r6 = (pixel >> 1) & 0x3;
        let g6 = (pixel >> 4) & 0x3;
        let b6 = (pixel >> 6) & 0x3;
        let pix6 = r6 | (g6 << 2) | (b6 << 4);
        (pix6 & 0x3f) | self.store.vga_sync_bits
    }

    fn copy_image_row(dest: &mut [u8], src: &[u8], mirror: bool) {
        if mirror {
            for (d, s) in dest.iter_mut().zip(src.iter().rev()) {
                *d = *s;
            }
        } else {
            for (d, s) in dest.iter_mut().zip(src.iter()) {
                *d = *s;
            }
        }
    }

    fn write_image_item_6bits(&self, width: u32, height: u32, item_num: u32, pixels: &[u8], mirror: bool) {
        let empty_pixel = self.store.vga_sync_bits as u32;
        let empty_quad = empty_pixel | empty_pixel << 8 | empty_pixel << 16 | empty_pixel << 24;
        let width = width as usize;
        let height = height as usize;
        let item_num = item_num as usize;
        let stride = width.div_ceil(4);
        let mut image_row = vec![self.store.vga_sync_bits; width];
        for y in 0..height {
            let index = (item_num * height + y) * width;
            Self::copy_image_row(&mut image_row, &pixels[index..index+width], mirror);
            for s in 0..stride {
                if s.is_multiple_of(8) { self.write("\n  "); }
                let mut quad = empty_quad | (self.pixel_to_6bpp(image_row[s*4]) as u32);
                if width > s*4+1 { quad |= (self.pixel_to_6bpp(image_row[s*4 + 1]) as u32) <<  8; }
                if width > s*4+2 { quad |= (self.pixel_to_6bpp(image_row[s*4 + 2]) as u32) << 16; }
                if width > s*4+3 { quad |= (self.pixel_to_6bpp(image_row[s*4 + 3]) as u32) << 24; }
                self.write(format!("{:#10x},", quad));
            }
        }
        self.write("\n");
    }

    fn write_image_item_8bits(&self, width: u32, height: u32, item_num: u32, pixels: &[u8], mirror: bool) {
        let width = width as usize;
        let height = height as usize;
        let item_num = item_num as usize;
        let stride = width.div_ceil(4);
        let mut image_row = vec![self.store.vga_sync_bits; width];
        for y in 0..height {
            let index = (item_num * height + y) * width;
            Self::copy_image_row(&mut image_row, &pixels[index..index+width], mirror);
            for s in 0..stride {
                if s.is_multiple_of(8) { self.write("\n  "); }
                let mut quad = image_row[s*4] as u32;
                if width > s*4+1 { quad |= (image_row[s*4 + 1] as u32) <<  8; }
                if width > s*4+2 { quad |= (image_row[s*4 + 2] as u32) << 16; }
                if width > s*4+3 { quad |= (image_row[s*4 + 3] as u32) << 24; }
                self.write(format!("{:#10x},", quad));
            }
        }
        self.write("\n");
    }

    fn write_image_item(&self, width: u32, height: u32, item_num: u32, pixels: &[u8], mirror: bool) {
        if self.store.vga_bits_per_pixel == 8 {
            self.write_image_item_8bits(width, height, item_num, pixels, mirror);
        } else {
            self.write_image_item_6bits(width, height, item_num, pixels, mirror);
        }
    }

    // =========================================================================
    // === FONT
    // =========================================================================

    fn write_font_data(&self, font: &super::Font, name: &str) {
        self.write(format!("static const uint8_t {}_font_data_{}[] = {{\n", self.ident.prefix_lower, name));
        for ch in 0..super::Font::NUM_CHARS {
            self.write("  ");
            for y in 0..font.height {
                let mut byte = 0;
                for x in 0..font.width {
                    let pixel = font.data[((ch * font.height + y) * font.width + x) as usize];
                    byte |= if pixel == super::Font::FG_COLOR { 1<<(x%8) } else { 0 };
                    if x % 8 == 7 {
                        self.write(format!("{:#04x},", byte));
                        byte = 0;
                    }
                }
                if ! font.width.is_multiple_of(8) {
                    self.write(format!("{:#04x},", byte));
                }
            }
            if (ch + super::Font::FIRST_CHAR) < 127 {
                self.write(format!("  // '{}'\n", char::from_u32(ch + super::Font::FIRST_CHAR).unwrap_or('?')));
            } else {
                self.write("  // DEL\n");
            }
        }
        self.write("};\n");
        self.write("\n");
    }

    fn write_fonts(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === FONTS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.fonts.iter() {
            if let Some(font) = self.store.assets.fonts.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Font, *id)?;
                self.log(format!("-> writing font data for '{}'", name_id));
                self.write_font_data(font, name_id);
            }
        }

        self.log(format!("-> writing {} fonts", self.store.asset_ids.fonts.len()));
        self.write(format!("const struct {}_FONT {}_fonts[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.fonts.iter() {
            if let Some(font) = self.store.assets.fonts.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Font, *id)?;
                self.write(format!("  {{ {}, {}, {}_font_data_{} }},\n", font.width, font.height, self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");
        Ok(())
    }

    // =========================================================================
    // === PROP FONT
    // =========================================================================

    fn write_prop_font_data(&self, font: &super::PropFont, name_id: &str) -> Vec::<u16> {
        self.write(format!("static const uint8_t {}_prop_font_data_{}[] = {{\n", self.ident.prefix_lower, name_id));
        let mut char_offset = 0;
        let mut char_offsets = Vec::<u16>::new();
        for ch in 0..super::PropFont::NUM_CHARS {
            char_offsets.push(char_offset);
            self.write("  ");
            for y in 0..font.height {
                let width = font.char_widths[ch as usize] as u32;
                let mut byte = 0;
                for x in 0..width {
                    let pixel = font.data[((ch * font.height + y) * font.max_width + x) as usize];
                    byte |= if pixel == super::PropFont::FG_COLOR { 1<<(x%8) } else { 0 };
                    if x % 8 == 7 {
                        self.write(format!("{:#04x},", byte));
                        byte = 0;
                        char_offset += 1;
                    }
                }
                if ! width.is_multiple_of(8) {
                    self.write(format!("{:#04x},", byte));
                    char_offset += 1;
                }
            }
            if (ch + super::PropFont::FIRST_CHAR) < 127 {
                self.write(format!("  // '{}'\n", char::from_u32(ch + super::PropFont::FIRST_CHAR).unwrap_or('?')));
            } else {
                self.write("  // DEL\n");
            }
        }
        self.write("};\n");
        self.write("\n");
        char_offsets
    }

    fn write_prop_fonts(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === PROPORTIONAL FONTS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        let mut font_char_offsets = HashMap::<DataAssetId, Vec<u16>>::new();
        for id in self.store.asset_ids.prop_fonts.iter() {
            if let Some(font) = self.store.assets.prop_fonts.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::PropFont, *id)?;
                self.log(format!("-> writing prop font data for '{}'", name_id));
                let char_offsets = self.write_prop_font_data(font, name_id);
                font_char_offsets.insert(*id, char_offsets);
            }
        }

        self.log(format!("-> writing {} prop fonts", self.store.asset_ids.prop_fonts.len()));
        self.write(format!("const struct {}_PROP_FONT {}_prop_fonts[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.prop_fonts.iter() {
            if let Some(font) = self.store.assets.prop_fonts.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::PropFont, *id)?;
                let char_offsets = font_char_offsets.get(id).ok_or_else(|| {
                    Error::other(format!("can't find char offset for pfont '{}'", id))
                })?;
                self.write("  {\n");
                self.write(format!("    {},\n", font.height));
                self.write(format!("    {}_prop_font_data_{},\n", self.ident.prefix_lower, name_id));
                self.write("    {  // char widths");
                for ch in 0..super::PropFont::NUM_CHARS {
                    if ch.is_multiple_of(24) { self.write("\n      "); }
                    self.write(format!("{},", font.char_widths[ch as usize]));
                }
                self.write("\n    },\n");
                self.write("    {  // char offsets");
                for ch in 0..super::PropFont::NUM_CHARS {
                    if ch.is_multiple_of(8) { self.write("\n      "); }
                    self.write(format!("{:>4},", char_offsets[ch as usize]));
                }
                self.write("\n    }\n");
                self.write("  },\n");
            }
        }
        self.write("};\n");
        self.write("\n");
        Ok(())
    }

    // =========================================================================
    // === MOD
    // =========================================================================

    // build the references for each
    fn get_mod_sample_refs(&mut self) -> HashMap<DataAssetId,Vec<ModSampleRef>> {
        let mod_ids: Vec::<DataAssetId> = self.store.asset_ids.mods.iter().copied().collect();

        let mut all_samples = HashMap::new();
        for mod_id in mod_ids.iter() {
            if let Some(mod_data) = self.store.assets.mods.get(mod_id) {
                let mut mod_samples = Vec::new();
                for sample_index in 0..mod_data.samples.len() {
                    mod_samples.push(ModSampleRef { mod_id: *mod_id, sample_index });
                }
                all_samples.insert(*mod_id, mod_samples);
            }
        }

        for (mod1_index, mod1_id) in mod_ids.iter().enumerate() {
            if let Some(mod1_data) = self.store.assets.mods.get(mod1_id) {
                for (mod2_index, mod2_id) in mod_ids.iter().enumerate().skip(mod1_index+1) {
                    if let Some(mod2_data) = self.store.assets.mods.get(mod2_id) {
                        for (sample1_index, sample1) in mod1_data.samples.iter().enumerate() {
                            if sample1.len == 0 || sample1.data.is_none() { continue; }
                            for (sample2_index, sample2) in mod2_data.samples.iter().enumerate() {
                                if sample2.len == 0 || sample2.data.is_none() { continue; }
                                if super::ModData::are_mod_samples_equal(sample1, sample2) {
                                    self.log(format!("-> merging mod samples: (mod{}:sample{}) to (mod{}:sample{})",
                                                     mod2_index+1, sample2_index+1, mod1_index+1, sample1_index+1));
                                    if let Some(mod2_samples) = all_samples.get_mut(mod2_id) {
                                        mod2_samples[sample2_index] = ModSampleRef {
                                            mod_id: *mod1_id,
                                            sample_index: sample1_index,
                                        };
                                        self.merge_sample_saved_size += (sample2.len * (sample2.bits_per_sample/8) as u32) as usize;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        all_samples
    }

    fn write_mod_samples_data(&self, mod_data: &super::ModData, name_id: &str, sample_refs: &[ModSampleRef]) {
        for (index, sample) in mod_data.samples.iter().enumerate() {
            if let Some(sample_ref) = sample_refs.get(index) {
                if sample_ref.mod_id != mod_data.asset.id || sample_ref.sample_index != index {
                    continue;  // skip this sample; it's been merged with another
                }
                if let Some(data) = &sample.data {
                    self.write(format!("static const int{}_t {}_mod_samples_{}_sample{:02}[] = {{",
                                       sample.bits_per_sample, self.ident.prefix_lower, name_id, index+1));
                    for (i, spl) in data.iter().enumerate() {
                        if i.is_multiple_of(16) { self.write("\n  "); }
                        if sample.bits_per_sample == 16 {
                            self.write(format!("{},", spl));
                        } else {
                            self.write(format!("{},", spl>>8));
                        }
                    }
                    self.write("\n};\n");
                    self.write("\n");
                }
            }
        }
    }

    fn write_mod_pattern(&self, mod_data: &super::ModData, name_id: &str) {
        self.write(format!("static const struct {}_MOD_CELL {}_mod_pattern_{}[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower, name_id));
        let num_channels = mod_data.num_channels as usize;
        let num_patterns = mod_data.pattern.len().div_ceil(64 * num_channels);
        for pattern_num in 0..num_patterns {
            self.write(format!("  // pattern {}\n", pattern_num));
            for row in 0..64 {
                self.write("  ");
                for ch in 0..num_channels {
                    let cell_index = (64 * pattern_num + row) * num_channels + ch;
                    if cell_index >= mod_data.pattern.len() { break; }
                    let cell = mod_data.pattern[cell_index];
                    let note_index = if cell.period == 0 {
                        0xff
                    } else {
                        let (note, octave) = super::ModData::get_period_note(cell.period);
                        if note < 0 || octave < 0 { 0xff } else { note + octave * 12 }
                    };
                    self.write(format!("{{ {:>2}, {:#04x}, {:#05x}, }}, ", cell.sample, note_index, cell.effect));
                }
                self.write("\n");
            }
        }
        self.write("};\n");
        self.write("\n");
    }

    fn write_mod_samples(&self, mod_data: &super::ModData, sample_refs: &[ModSampleRef]) -> Result<()> {
        for (index, sample) in mod_data.samples.iter().enumerate() {
            self.write(format!("      {{{:>6},{:>6},{:>6}, {:#04x}, {:>2}, {:>2},",
                               sample.len, sample.loop_start, sample.loop_len,
                               if sample.finetune < 0 { sample.finetune + 16 } else { sample.finetune },
                               sample.volume, sample.bits_per_sample));
            if sample.len == 0 || sample.data.is_none() {
                self.write(" { .data = NULL }, },\n");
                continue;
            }
            if let Some(sample_ref) = sample_refs.get(index) {
                let sample_ref_mod_name_id = self.ident.get_asset_name_id(DataAssetType::ModData, sample_ref.mod_id)?;
                self.write(format!(" {{ .data{} = {}_mod_samples_{}_sample{:02} }}, }},\n",
                                   sample.bits_per_sample, self.ident.prefix_lower,
                                   sample_ref_mod_name_id, sample_ref.sample_index+1));
            }
        }
        Ok(())
    }

    fn write_mods(&mut self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === MOD\n");
        self.write("// ================================================================\n");
        self.write("\n");

        // samples
        let mod_sample_refs = self.get_mod_sample_refs();
        for id in self.store.asset_ids.mods.iter() {
            if let Some(mod_data) = self.store.assets.mods.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::ModData, *id)?;
                let sample_refs = mod_sample_refs.get(id).ok_or_else(|| {
                    Error::other(format!("can't find sample refs for mod {}", id))
                })?;
                self.write_mod_samples_data(mod_data, name_id, sample_refs);
            }
        }

        // patterns
        for id in self.store.asset_ids.mods.iter() {
            if let Some(mod_data) = self.store.assets.mods.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::ModData, *id)?;
                self.write_mod_pattern(mod_data, name_id);
            }
        }

        // mods
        self.log(format!("-> writing {} mods", self.store.asset_ids.mods.len()));
        self.write(format!("const struct {}_MOD_DATA {}_mods[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.mods.iter() {
            if let Some(mod_data) = self.store.assets.mods.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::ModData, *id)?;
                self.write("  {\n");
                self.write("    // samples:\n");
                self.write("    {\n");
                if let Some(sample_refs) = mod_sample_refs.get(id) {
                    self.write_mod_samples(mod_data, sample_refs)?;
                }
                self.write("    },\n");
                self.write("    // num channels:\n");
                self.write(format!("    {},\n", mod_data.num_channels));
                self.write("    // song positions:\n");
                self.write(format!("    {}, {{", mod_data.song_positions.len()));
                for (index, song_pos) in mod_data.song_positions.iter().enumerate() {
                    if index.is_multiple_of(16) { self.write("\n      "); }
                    self.write(format!("{:>3},", song_pos));
                }
                self.write("\n");
                self.write("    },\n");
                self.write("    // pattern:\n");
                self.write(format!("    {}, {}_mod_pattern_{},\n",
                                   mod_data.pattern.len().div_ceil(64*mod_data.num_channels as usize),
                                   self.ident.prefix_lower, name_id));
                self.write("  },\n");
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    // =========================================================================
    // === SFX
    // =========================================================================

    fn write_sfx_data(&self, sfx: &super::Sfx, name_id: &str) {
        self.write(format!("static const int{}_t {}_sfx_samples_{}[] = {{",
                           sfx.bits_per_sample, self.ident.prefix_lower, name_id));
        for (i, spl) in sfx.samples.iter().enumerate() {
            if i.is_multiple_of(16) { self.write("\n  "); }
            if sfx.bits_per_sample == 16 {
                self.write(format!("{},", spl));
            } else {
                self.write(format!("{},", spl>>8));
            }
        }
        self.write("\n};\n");
        self.write("\n");
    }

    fn write_sfxs(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === SFX\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.sfxs.iter() {
            if let Some(sfx) = self.store.assets.sfxs.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Sfx, *id)?;
                self.write_sfx_data(sfx, name_id);
            }
        }

        self.log(format!("-> writing {} sfxs", self.store.asset_ids.sfxs.len()));
        self.write(format!("const struct {}_SFX {}_sfxs[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.sfxs.iter() {
            if let Some(sfx) = self.store.assets.sfxs.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Sfx, *id)?;
                self.write(format!("  {{{:>6},{:>5},{:>5}, {}, {{ .spl{} = {}_sfx_samples_{} }} }},\n",
                                   sfx.len, sfx.loop_start, sfx.loop_len, sfx.bits_per_sample,
                                   sfx.bits_per_sample, self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    // =========================================================================
    // === TILESET
    // =========================================================================

    fn write_tileset_data(&self, tileset: &super::Tileset, name_id: &str) {
        self.write(format!("static const uint32_t {}_tileset_data_{}[] = {{\n",
                           self.ident.prefix_lower, name_id));
        for tile_num in 0..tileset.num_tiles {
            self.write(format!("  // tile {}", tile_num));
            self.write_image_item(tileset.width, tileset.height, tile_num, &tileset.data, false);
        }
        self.write("};\n");
        self.write("\n");
    }

    fn write_tilesets(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === TILESETS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.tilesets.iter() {
            if let Some(tileset) = self.store.assets.tilesets.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Tileset, *id)?;
                self.write_tileset_data(tileset, name_id);
            }
        }

        self.log(format!("-> writing {} tilesets", self.store.asset_ids.tilesets.len()));
        self.write(format!("const struct {}_IMAGE {}_tilesets[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.tilesets.iter() {
            if let Some(tileset) = self.store.assets.tilesets.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Tileset, *id)?;
                self.write(format!("  {{ {}, {}, {}, {}, {}_tileset_data_{} }},\n",
                                   tileset.width, tileset.height, tileset.width.div_ceil(4), tileset.num_tiles,
                                   self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");
        Ok(())
    }

    // =========================================================================
    // === SPRITE
    // =========================================================================

    fn write_sprite_frames(&self, sprite: &super::Sprite, mirror: bool) {
        for frame_num in 0..sprite.num_frames {
            self.write(format!("  // frame {}{}", frame_num, if mirror { " (mirror)" } else { "" }));
            self.write_image_item(sprite.width, sprite.height, frame_num, &sprite.data, mirror);
        }
    }

    fn write_sprite_data(&self, sprite: &super::Sprite, name_id: &str) {
        self.write(format!("static const uint32_t {}_sprite_data_{}[] = {{\n",
                           self.ident.prefix_lower, name_id));
        self.write_sprite_frames(sprite, false);
        if super::Sprite::MIRROR_FRAMES {
            self.write_sprite_frames(sprite, true);
        }
        self.write("};\n");
        self.write("\n");
    }

    fn write_sprites(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === SPRITES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.sprites.iter() {
            if let Some(sprite) = self.store.assets.sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Sprite, *id)?;
                self.write_sprite_data(sprite, name_id);
            }
        }

        self.log(format!("-> writing {} sprites", self.store.asset_ids.sprites.len()));
        let mult_mirrors = if super::Sprite::MIRROR_FRAMES { 2 } else { 1 };
        self.write(format!("const struct {}_IMAGE {}_sprites[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.sprites.iter() {
            if let Some(sprite) = self.store.assets.sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Sprite, *id)?;
                self.write(format!("  {{ {}, {}, {}, {}, {}_sprite_data_{} }},\n",
                                   sprite.width, sprite.height, sprite.width.div_ceil(4), sprite.num_frames * mult_mirrors,
                                   self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    // =========================================================================
    // === PALETTED SPRITE
    // =========================================================================

    fn write_pal_sprite_frames(&self, pal_sprite: &super::PalSprite) {
        let bits_per_pixel = pal_sprite.depth.bits_per_pixel();
        let stride = (pal_sprite.width * bits_per_pixel).div_ceil(8);
        let pixels_per_byte = 8 / bits_per_pixel;

        let mut src_index = 0;
        for frame_num in 0..pal_sprite.num_frames {
            self.write(format!("  // frame {}", frame_num));
            for _ in 0..pal_sprite.height {
                self.write("\n  ");
                for byte_num in 0..stride {
                    let mut block = 0u8;
                    for pix_num in 0..pixels_per_byte {
                        if byte_num * pixels_per_byte + pix_num >= pal_sprite.width { break; }
                        let color = pal_sprite.data[src_index];
                        src_index += 1;
                        block |= pal_sprite.color_to_palette_index(color) << (pix_num * bits_per_pixel);
                    }
                    self.write(format!("{:#04x},", block));
                }
            }
            self.write("\n");
        }
    }

    fn write_pal_sprite_data(&self, pal_sprite: &super::PalSprite, name_id: &str) {
        self.write(format!("static const uint8_t {}_pal_sprite_data_{}[] = {{\n",
                           self.ident.prefix_lower, name_id));
        self.write_pal_sprite_frames(pal_sprite);
        self.write("};\n");
        self.write("\n");
    }

    fn write_pal_sprites(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === PALETTED SPRITES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.pal_sprites.iter() {
            if let Some(pal_sprite) = self.store.assets.pal_sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::PalSprite, *id)?;
                self.write_pal_sprite_data(pal_sprite, name_id);
            }
        }

        self.log(format!("-> writing {} pal_sprites", self.store.asset_ids.pal_sprites.len()));
        self.write(format!("const struct {}_PAL_SPRITE {}_pal_sprites[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.pal_sprites.iter() {
            if let Some(pal_sprite) = self.store.assets.pal_sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::PalSprite, *id)?;
                self.write("  {\n");
                self.write(format!("    {}, {}, {}, {},\n",  pal_sprite.width, pal_sprite.height,
                                   pal_sprite.num_frames, pal_sprite.depth.bits_per_pixel()));
                self.write("    { ");
                for color in &pal_sprite.palette {
                    self.write(format!("{:#04x},", color));
                }
                self.write(" },\n");
                self.write(format!("    {}_pal_sprite_data_{}\n",
                                   self.ident.prefix_lower, name_id));
                self.write("  },\n");
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    // =========================================================================
    // === MAP
    // =========================================================================

    fn write_map_tiles(&self, tiles: &[u8]) {
        for (index, tile) in tiles.iter().enumerate() {
            if index.is_multiple_of(16) { self.write("\n  "); }
            self.write(format!("{:#04x},", tile))
        }
    }

    fn write_map_data(&self, map_data: &super::MapData, name_id: &str) {
        self.write(format!("static const uint8_t {}_map_tiles_{}[] = {{", self.ident.prefix_lower, name_id));
        self.write("\n  // foreground");
        self.write_map_tiles(&map_data.fg_tiles);
        self.write("\n  // background");
        self.write_map_tiles(&map_data.bg_tiles);
        self.write("\n  // effects");
        self.write_map_tiles(&map_data.fx_tiles);
        self.write("\n  // parallax");
        self.write_map_tiles(&map_data.para_tiles);
        self.write("\n};\n");
        self.write("\n");
    }

    fn write_maps(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === MAPS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.maps.iter() {
            if let Some(map_data) = self.store.assets.maps.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::MapData, *id)?;
                self.write_map_data(map_data, name_id);
            }
        }

        self.log(format!("-> writing {} maps", self.store.asset_ids.maps.len()));
        self.write(format!("const struct {}_MAP {}_maps[] = {{\n", self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.maps.iter() {
            if let Some(map_data) = self.store.assets.maps.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::MapData, *id)?;
                let tileset_index = self.ident.get_asset_index(DataAssetType::Tileset, map_data.tileset_id)?;
                self.write(format!("  {{ {}, {}, {}, {}, &{}_tilesets[{}], {}_map_tiles_{} }},\n",
                                   map_data.width, map_data.height, map_data.para_width, map_data.para_height,
                                   self.ident.prefix_lower, tileset_index,
                                   self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    // =========================================================================
    // === SPRITE ANIMATION
    // =========================================================================

    fn write_animation_frames(&self, anim: &super::SpriteAnimation, name_id: &str) -> AnimationInfo {
        let add_foot = anim.loops.iter().any(|l| l.frame_indices.iter().any(|f| f.foot_index.is_some()));
        let mut loop_offsets = Vec::new();
        let mut loop_index_to_name_id = HashMap::new();

        self.write(format!("static const uint8_t {}_sprite_animation_frames_{}[] = {{\n",
                           self.ident.prefix_lower, name_id));
        let mut offset = 0;
        for (loop_index, aloop) in anim.loops.iter().enumerate() {
            let use_loop_name_id = if aloop.name_id == "names" { "names0" } else { &aloop.name_id };
            IdentStore::add_unique_name_id(loop_index, use_loop_name_id, &mut loop_index_to_name_id);
            if aloop.frame_indices.is_empty() { continue; }
            self.write(format!("  // {}\n  ", aloop.name_id));
            for frame in aloop.frame_indices.iter() {
                self.write(format!("{:#04x},", frame.head_index.unwrap_or(0xff)));
                if add_foot {
                    self.write(format!("{:#04x},", frame.foot_index.unwrap_or(0xff)));
                }
            }
            self.write("\n");
            loop_offsets.push(offset);
            offset += aloop.frame_indices.len() * if add_foot { 2 } else { 1 };
        }
        self.write("};\n");
        self.write("\n");

        AnimationInfo {
            add_foot,
            loop_offsets,
            loop_index_to_name_id,
        }
    }

    fn write_sprite_animations(&mut self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === SPRITE ANIMATIONS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.animations.iter() {
            if let Some(anim) = self.store.assets.animations.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::SpriteAnimation, *id)?;
                self.animation_info.insert(*id, self.write_animation_frames(anim, name_id));
            }
        }

        self.log(format!("-> writing {} animations", self.store.asset_ids.animations.len()));
        self.write(format!("const struct {}_SPRITE_ANIMATION {}_sprite_animations[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.animations.iter() {
            if let Some(anim) = self.store.assets.animations.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::SpriteAnimation, *id)?;
                let sprite_index = self.ident.get_asset_index(DataAssetType::Sprite, anim.sprite_id)?;
                let info = self.animation_info.get(id).ok_or_else(|| {
                    Error::other(format!("can't find info for animation {}", id))
                })?;
                self.write("  {\n");
                self.write(format!("    {}_sprite_animation_frames_{},\n", self.ident.prefix_lower, name_id));
                self.write(format!("    &{}_sprites[{}],\n", self.ident.prefix_lower, sprite_index));
                self.write(format!("    {{ {}, {}, {}, {} }},\n", anim.clip_rect.x, anim.clip_rect.y, anim.clip_rect.w, anim.clip_rect.h));
                self.write(format!("    {},\n", if info.add_foot { 1 } else { 0 }));
                self.write(format!("    {},\n", anim.foot_overlap));
                self.write("    {\n");
                let mut last_offset = 0;
                for (loop_index, aloop) in anim.loops.iter().enumerate() {
                    let loop_name_id = info.loop_index_to_name_id.get(&loop_index).ok_or_else(|| {
                        Error::other(format!("can't find loop name {} for animation {}", loop_index, id))
                    })?;
                    let loop_offset = info.loop_offsets.get(loop_index).copied().unwrap_or(last_offset);
                    if ! aloop.frame_indices.is_empty() {
                        self.write(format!("      {{ {:>5}, {:>5} }}, // {}\n", loop_offset, aloop.frame_indices.len(), loop_name_id));
                    } else {
                        self.write(format!("      {{ {:>5}, {:>5} }},\n", loop_offset, aloop.frame_indices.len()));
                    }
                    last_offset = loop_offset + aloop.frame_indices.len();
                }
                self.write("    }\n");
                self.write("  },\n");
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_animation_names(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === SPRITE ANIMATION LOOP NAMES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.animations.iter() {
            if let Some(anim) = self.store.assets.animations.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::SpriteAnimation, *id)?;
                let info = self.animation_info.get(id).ok_or_else(|| {
                    Error::other(format!("error reading loop names for animation {}", id))
                })?;
                let name_id_upper = name_id.to_ascii_uppercase();
                let mut num_named_loops = 0;
                for loop_index in (0..anim.loops.len()).rev() {
                    let loop_name = info.loop_index_to_name_id.get(&loop_index).ok_or_else(|| {
                        Error::other(format!("error reading name for loop {} of animation {}", loop_index, id))
                    })?;
                    if ! RE_UNNAMED_LOOP.is_match(loop_name) {
                        num_named_loops = loop_index + 1;
                        break;
                    }
                }
                if num_named_loops == 0 { continue; }

                self.write(format!("enum {}_SPRITE_ANIMATION_{}_LOOP_NAMES {{\n", self.ident.prefix_upper, name_id_upper));
                for loop_index in 0..num_named_loops {
                    let loop_name_id = info.loop_index_to_name_id.get(&loop_index).ok_or_else(|| {
                        Error::other(format!("error reading name for loop {} of animation {}", loop_index, id))
                    })?;
                    let loop_name_id_upper = loop_name_id.to_ascii_uppercase();
                    self.write(format!("  {}_SPRITE_ANIMATION_{}_LOOP_{},\n", self.ident.prefix_upper, name_id_upper, loop_name_id_upper));
                }
                self.write("};\n");
                self.write("\n");
            }
        }

        Ok(())
    }

    // =========================================================================
    // === ROOM
    // =========================================================================

    fn write_room_maps(&self, room: &super::Room, name_id: &str) -> Result<()> {
        self.write(format!("static const struct {}_ROOM_MAP_INFO {}_room_maps_{}[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower, name_id));
        for room_map in room.maps.iter() {
            let map_index = self.ident.get_asset_index(DataAssetType::MapData, room_map.map_id)?;
            self.write(format!("  {{ {}, {}, &{}_maps[{}] }},\n", room_map.x, room_map.y, self.ident.prefix_lower, map_index));
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_room_triggers(&self, room: &super::Room, name_id: &str) -> Result<()> {
        self.write(format!("static const struct {}_ROOM_TRIGGER_INFO {}_room_triggers_{}[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower, name_id));
        for trg in room.triggers.iter() {
            let enum_type_ident = super::RoomTriggerTypeIdent::from_trigger_type(&trg.trigger_type).enum_ident();

            self.write("  {  ");
            self.write(format!("{}_{}, {}, {}, ", self.ident.prefix_upper, enum_type_ident, trg.x, trg.y));
            match trg.trigger_type {
                RoomTriggerType::Unknown { data0, data1, data2, data3 } => {
                    self.write(format!(".any = {{ {}, {}, {}, {} }}",
                                       data0, data1, data2, data3));
                }
                RoomTriggerType::Door { room_id, door_id } => {
                    let room_index = self.ident.get_asset_index(DataAssetType::Room, room_id)?;
                    self.write(format!(".door = {{ &{}_rooms[{}], {} }}",
                                       self.ident.prefix_lower, room_index, door_id));
                }
                RoomTriggerType::PlayerSpawn { direction } => {
                    self.write(format!(".player_spawn = {{ {} }}", direction));
                }
                RoomTriggerType::EnemySpawn { animation_id } => {
                    let animation_index = self.ident.get_asset_index(DataAssetType::SpriteAnimation, animation_id)?;
                    self.write(format!(".enemy_spawn = {{ &{}_sprite_animations[{}] }}",
                                       self.ident.prefix_lower, animation_index));
                }
                RoomTriggerType::Trap { width, height, type_id } => {
                    self.write(format!(".trap = {{ {}, {}, {} }}", width, height, type_id ));
                }
            }
            self.write(" },\n");
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_rooms(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === ROOMS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.rooms.iter() {
            if let Some(room) = self.store.assets.rooms.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Room, *id)?;
                self.write_room_maps(room, name_id)?;
                self.write_room_triggers(room, name_id)?;
            }
        }

        self.log(format!("-> writing {} rooms", self.store.asset_ids.rooms.len()));
        self.write(format!("const struct {}_ROOM {}_rooms[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.rooms.iter() {
            if let Some(room) = self.store.assets.rooms.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Room, *id)?;
                self.write(format!("  {{ {}, {}, {}_room_maps_{}, {}_room_triggers_{} }},\n",
                                   room.maps.len(), room.triggers.len(),
                                   self.ident.prefix_lower, name_id, self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_room_trigger_names(&self, room: &super::Room, name_id_upper: &str) -> Result<()> {
        let mut index_to_name_id = HashMap::new();

        self.write(format!("enum {}_ROOM_{}_TRG_NAMES {{\n", self.ident.prefix_upper, name_id_upper));
        for (index, trg) in room.triggers.iter().enumerate() {
            let use_name_id = if trg.name_id == "names" { "names0" } else { &trg.name_id };
            IdentStore::add_unique_name_id(index, use_name_id, &mut index_to_name_id);
            let trg_name_id = index_to_name_id.get(&index).ok_or_else(|| {
                Error::other(format!("error reading name of trigger {} room {}", index, room.asset.id))
            })?;
            self.write(format!("  {}_ROOM_{}_TRG_{},\n", self.ident.prefix_upper, name_id_upper, trg_name_id.to_ascii_uppercase()));
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_room_item_names(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === ROOM ITEM NAMES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.rooms.iter() {
            if let Some(room) = self.store.assets.rooms.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Room, *id)?;
                let name_id_upper = name_id.to_ascii_uppercase();
                self.write_room_trigger_names(room, &name_id_upper)?;
            }
        }

        Ok(())
    }

    // =========================================================================
    // === WORLDS
    // =========================================================================

    fn write_world_region_block_bitmap(&self, region: &super::WorldRegion, region_index: usize, world_name_id: &str) -> Result<()> {
        self.write(format!("static const uint32_t {}_world_{}_region_{}_block_bitmap[] = {{",
                           self.ident.prefix_lower, world_name_id, region_index));
        let mut bits = 0;
        let mut num_bits = 0;
        let mut num_chunks = 0;
        for y in 0..region.height as usize {
            for x in 0..region.width as usize {
                if region.blocks[y * super::WorldRegion::BLOCK_STRIDE + x].is_some() {
                    bits |= 1 << num_bits;
                }
                num_bits += 1;
                if num_bits == 32 {
                    if num_chunks % 8 == 0 { self.write("\n    "); }
                    self.write(format!("{:#010x},", bits));
                    bits = 0;
                    num_bits = 0;
                    num_chunks += 1;
                }
            }
        }
        if num_bits != 0 {
            if num_chunks % 8 == 0 { self.write("\n    "); }
            self.write(format!("{:#010x},", bits));
        }

        self.write("\n};\n\n");
        Ok(())
    }

    fn write_world_region_blocks(&self, region: &super::WorldRegion, region_index: usize, world_name_id: &str) -> Result<()> {
        self.write(format!("static const uint8_t {}_world_{}_region_{}_blocks[] = {{",
                           self.ident.prefix_lower, world_name_id, region_index));

        let mut num_blocks_written = 0;
        for y in 0..region.height as usize {
            for x in 0..region.width as usize {
                if let Some(block) = region.blocks[y * super::WorldRegion::BLOCK_STRIDE + x] {
                    if num_blocks_written % 16 == 0 { self.write("\n    "); }
                    self.write(format!("{:#04x},", block));
                    num_blocks_written += 1;
                }
            }
        }
        self.write("\n};\n\n");
        Ok(())
    }

    fn write_world_region_room_indices(&self, region: &super::WorldRegion, region_index: usize, world_name_id: &str) -> Result<()> {
        self.write(format!("static const uint16_t {}_world_{}_region_{}_room_indices[] = {{",
                           self.ident.prefix_lower, world_name_id, region_index));
        for (index, &room_id) in region.rooms.iter().enumerate() {
            if index % 16 == 0 { self.write("\n    "); }
            let room_index = self.ident.get_asset_index(DataAssetType::Room, room_id)?;
            self.write(format!("{},", room_index));
        }
        self.write("\n};\n\n");
        Ok(())
    }

    fn write_world_regions(&self, world: &super::World, name_id: &str) -> Result<()> {
        for (region_index, region) in world.regions.iter().enumerate() {
            self.write_world_region_block_bitmap(region, region_index, name_id)?;
            self.write_world_region_blocks(region, region_index, name_id)?;
            self.write_world_region_room_indices(region, region_index, name_id)?;
        }

        self.write(format!("static const struct {}_WORLD_REGION {}_world_regions_{}[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower, name_id));
        for (region_index, region) in world.regions.iter().enumerate() {
            self.write("  {\n");
            self.write(format!("    {}, {}, {}, {},\n", region.x, region.y, region.width, region.height));
            self.write(format!("    {}_world_{}_region_{}_block_bitmap,\n", self.ident.prefix_lower, name_id, region_index));
            self.write(format!("    {}_world_{}_region_{}_blocks,\n", self.ident.prefix_lower, name_id, region_index));
            self.write(format!("    {}_world_{}_region_{}_room_indices\n", self.ident.prefix_lower, name_id, region_index));
            self.write("  },\n");
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_worlds(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === WORLDS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.worlds.iter() {
            if let Some(world) = self.store.assets.worlds.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::World, *id)?;
                self.write_world_regions(world, name_id)?;
            }
        }

        self.log(format!("-> writing {} worlds", self.store.asset_ids.rooms.len()));
        self.write(format!("const struct {}_WORLD {}_worlds[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.worlds.iter() {
            if let Some(world) = self.store.assets.worlds.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::World, *id)?;
                self.write(format!("  {{ {}, {}_world_regions_{} }},\n",
                                   world.regions.len(),
                                   self.ident.prefix_lower, name_id));
            }
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_world_region_names(&self, world: &super::World, name_id_upper: &str) -> Result<()> {
        let mut index_to_name_id = HashMap::new();

        self.write(format!("enum {}_WORLD_{}_REGION_NAMES {{\n", self.ident.prefix_upper, name_id_upper));
        for (index, reg) in world.regions.iter().enumerate() {
            let use_name_id = if reg.name == "names" { "names0" } else { &reg.name };
            IdentStore::add_unique_name_id(index, use_name_id, &mut index_to_name_id);
            let reg_name_id = index_to_name_id.get(&index).ok_or_else(|| {
                Error::other(format!("error reading name of region {} world {}", index, world.asset.id))
            })?;
            self.write(format!("  {}_WORLD_{}_REGION_{},\n", self.ident.prefix_upper, name_id_upper, reg_name_id.to_ascii_uppercase()));
        }
        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_world_item_names(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === WORLD REGION NAMES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        for id in self.store.asset_ids.worlds.iter() {
            if let Some(world) = self.store.assets.worlds.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::World, *id)?;
                let name_id_upper = name_id.to_ascii_uppercase();
                self.write_world_region_names(world, &name_id_upper)?;
            }
        }

        Ok(())
    }

    // =========================================================================
    // === SCRIPTS
    // =========================================================================

    fn write_scripts(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === ROOM SCRIPTS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        self.write(format!("#if {}_ADD_ROOM_SCRIPTS\n", self.ident.prefix_upper));
        self.write("\n");

        for id in self.store.asset_ids.rooms.iter() {
            let name_id = self.ident.get_asset_name_id(DataAssetType::Room, *id)?;
            self.write(format!("extern const struct {}_ROOM_SCRIPT {}_room_script_table_{};\n",
                               self.ident.prefix_upper, self.ident.prefix_lower, name_id));
        }

        self.write("\n");
        self.write(format!("const struct {}_ROOM_SCRIPT *{}_room_script_table[] = {{\n",
                           self.ident.prefix_upper, self.ident.prefix_lower));
        for id in self.store.asset_ids.rooms.iter() {
            let name_id = self.ident.get_asset_name_id(DataAssetType::Room, *id)?;
            self.write(format!("  &{}_room_script_table_{},\n", self.ident.prefix_lower, name_id));
        }
        self.write("};\n");

        self.write("\n");
        self.write(format!("#endif /* {}_ADD_ROOM_SCRIPTS */\n", self.ident.prefix_upper));
        self.write("\n");

        Ok(())
    }

    // =========================================================================
    // === ASSET IDS
    // =========================================================================

    fn write_asset_ids_for(&self, asset_ids: &AssetIdList, asset_type: DataAssetType, type_name: &str) -> Result<()> {
        self.write(format!("enum {}_{}_IDS {{\n", self.ident.prefix_upper, type_name));
        for id in asset_ids.iter() {
            let name_id = self.ident.get_asset_name_id(asset_type, *id)?;
            let name_id_upper = name_id.to_ascii_uppercase();
            self.write(format!("  {}_{}_ID_{},\n", self.ident.prefix_upper, type_name, name_id_upper));
        }
        self.write(format!("  {}_{}_COUNT,\n", self.ident.prefix_upper, type_name));

        self.write("};\n");
        self.write("\n");

        Ok(())
    }

    fn write_asset_ids(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === IDS\n");
        self.write("// ================================================================\n");
        self.write("\n");

        self.write_asset_ids_for(&self.store.asset_ids.fonts, DataAssetType::Font, "FONT")?;
        self.write_asset_ids_for(&self.store.asset_ids.prop_fonts, DataAssetType::PropFont, "PROP_FONT")?;
        self.write_asset_ids_for(&self.store.asset_ids.mods, DataAssetType::ModData, "MOD")?;
        self.write_asset_ids_for(&self.store.asset_ids.sfxs, DataAssetType::Sfx, "SFX")?;
        self.write_asset_ids_for(&self.store.asset_ids.tilesets, DataAssetType::Tileset, "TILESET")?;
        self.write_asset_ids_for(&self.store.asset_ids.sprites, DataAssetType::Sprite, "SPRITE")?;
        self.write_asset_ids_for(&self.store.asset_ids.pal_sprites, DataAssetType::PalSprite, "PAL_SPRITE")?;
        self.write_asset_ids_for(&self.store.asset_ids.maps, DataAssetType::MapData, "MAP")?;
        self.write_asset_ids_for(&self.store.asset_ids.animations, DataAssetType::SpriteAnimation, "SPRITE_ANIMATION")?;
        self.write_asset_ids_for(&self.store.asset_ids.rooms, DataAssetType::Room, "ROOM")?;
        self.write_asset_ids_for(&self.store.asset_ids.worlds, DataAssetType::World, "WORLD")?;

        Ok(())
    }

    // =========================================================================
    // === IMAGE SIZES
    // =========================================================================

    fn write_sprite_sizes(&self) -> Result<()> {
        self.write("// ================================================================\n");
        self.write("// === SPRITE SIZES\n");
        self.write("// ================================================================\n");
        self.write("\n");

        let mult_mirrors = if super::Sprite::MIRROR_FRAMES { 2 } else { 1 };
        for id in self.store.asset_ids.sprites.iter() {
            if let Some(sprite) = self.store.assets.sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::Sprite, *id)?;
                let name_id_upper = name_id.to_ascii_uppercase();
                self.write(format!("#define {}_SPRITE_WIDTH_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.width));
                self.write(format!("#define {}_SPRITE_HEIGHT_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.height));
                self.write(format!("#define {}_SPRITE_STRIDE_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.width.div_ceil(4)));
                self.write(format!("#define {}_SPRITE_FRAMES_{} {}\n", self.ident.prefix_upper, name_id_upper, sprite.num_frames*mult_mirrors));
                self.write("\n");
            }
        }

        for id in self.store.asset_ids.pal_sprites.iter() {
            if let Some(pal_sprite) = self.store.assets.pal_sprites.get(id) {
                let name_id = self.ident.get_asset_name_id(DataAssetType::PalSprite, *id)?;
                let name_id_upper = name_id.to_ascii_uppercase();
                self.write(format!("#define {}_PAL_SPRITE_WIDTH_{} {}\n", self.ident.prefix_upper, name_id_upper, pal_sprite.width));
                self.write(format!("#define {}_PAL_SPRITE_HEIGHT_{} {}\n", self.ident.prefix_upper, name_id_upper, pal_sprite.height));
                self.write(format!("#define {}_PAL_SPRITE_FRAMES_{} {}\n", self.ident.prefix_upper, name_id_upper, pal_sprite.num_frames));
                self.write(format!("#define {}_PAL_SPRITE_DEPTH_{} {}\n", self.ident.prefix_upper, name_id_upper,
                                   pal_sprite.depth.bits_per_pixel()));
                self.write("\n");
            }
        }
        Ok(())
    }

    // =========================================================================
    // === PROJECT
    // =========================================================================

    fn gen_unique_asset_names(&mut self) -> Result<()> {
        self.ident.add_assets(DataAssetType::Tileset, self.store);
        self.ident.add_assets(DataAssetType::MapData, self.store);
        self.ident.add_assets(DataAssetType::Room, self.store);
        self.ident.add_assets(DataAssetType::World, self.store);
        self.ident.add_assets(DataAssetType::Sprite, self.store);
        self.ident.add_assets(DataAssetType::PalSprite, self.store);
        self.ident.add_assets(DataAssetType::SpriteAnimation, self.store);
        self.ident.add_assets(DataAssetType::Sfx, self.store);
        self.ident.add_assets(DataAssetType::ModData, self.store);
        self.ident.add_assets(DataAssetType::Font, self.store);
        self.ident.add_assets(DataAssetType::PropFont, self.store);
        Ok(())
    }

    fn serialize(mut self) -> Result<String> {
        self.gen_unique_asset_names()?;
        self.write_header()?;

        self.write_fonts()?;
        self.write_prop_fonts()?;
        self.write_pal_sprites()?;
        self.write_mods()?;
        self.write_sfxs()?;
        self.write_tilesets()?;
        self.write_sprites()?;
        self.write_maps()?;
        self.write_sprite_animations()?;
        self.write_rooms()?;
        self.write_worlds()?;

        self.write_scripts()?;

        self.write_data_end()?;

        self.write_animation_names()?;
        self.write_room_item_names()?;
        self.write_world_item_names()?;
        self.write_asset_ids()?;
        self.write_sprite_sizes()?;

        self.write_footer()?;
        Ok(self.output.take())
    }

    pub fn write_to_file<P: AsRef<Path>>(filename: P, store: &DataAssetStore, logger: &mut StringLogger) -> Result<()> {
        fn write_tmp_file(filename: &Path, data: &str) -> Result<()> {
            let mut file = fs::File::create(filename)?;
            file.write_all(data.as_bytes())?;
            file.sync_all()
        }

        let writer = ProjectDataWriter::new(store, logger);
        let content = writer.serialize()?;
        let tmp_filename = filename.as_ref().with_extension("h-tmp");
        match write_tmp_file(&tmp_filename, &content) {
            Ok(_) => {
                fs::rename(&tmp_filename, filename)
            }
            Err(e) => {
                if let Err(e) = fs::remove_file(tmp_filename) {
                    logger.log(format!("WARNING: error removing temp file: {}", e));
                }
                Err(e)
            }
        }
    }
}
