use crate::misc::IMAGE_REFS;
use crate::data_asset::DataAssetType;

pub struct AssetDef {
    pub asset_type: DataAssetType,
    pub default_name_prefix: &'static str,
    pub type_name: &'static str,
    pub add_menu_item: &'static str,
    pub duplicate_menu_item: &'static str,
    pub remove_menu_item: &'static str,
    pub rename_menu_item: &'static str,
    pub tree_root_item: &'static str,
    pub image: crate::misc::image_table::ImageRef,
}

pub const ASSET_DEFS : &[AssetDef] = &[
    AssetDef {
        asset_type: DataAssetType::Tileset,
        default_name_prefix: "tileset",
        type_name: "Tileset",
        add_menu_item: " Add Tileset",
        duplicate_menu_item: " Duplicate Tileset",
        remove_menu_item: " Delete Tileset",
        rename_menu_item: " Rename Tileset",
        tree_root_item: "Tilesets",
        image: IMAGE_REFS.tileset,
    },
    AssetDef {
        asset_type: DataAssetType::MapData,
        default_name_prefix: "map",
        type_name: "Map",
        add_menu_item: " Add Map",
        duplicate_menu_item: " Duplicate Map",
        remove_menu_item: " Delete Map",
        rename_menu_item: " Rename Map",
        tree_root_item: "Maps",
        image: IMAGE_REFS.map_data,
    },
    AssetDef {
        asset_type: DataAssetType::Room,
        default_name_prefix: "room",
        type_name: "Room",
        add_menu_item: " Add Room",
        duplicate_menu_item: " Duplicate Room",
        remove_menu_item: " Delete Room",
        rename_menu_item: " Rename Room",
        tree_root_item: "Rooms",
        image: IMAGE_REFS.room,
    },
    AssetDef {
        asset_type: DataAssetType::World,
        default_name_prefix: "world",
        type_name: "World",
        add_menu_item: " Add World",
        duplicate_menu_item: " Duplicate World",
        remove_menu_item: " Delete World",
        rename_menu_item: " Rename World",
        tree_root_item: "Worlds",
        image: IMAGE_REFS.world,
    },
    AssetDef {
        asset_type: DataAssetType::Sprite,
        default_name_prefix: "sprite",
        type_name: "Sprite",
        add_menu_item: " Add Sprite",
        duplicate_menu_item: " Duplicate Sprite",
        remove_menu_item: " Delete Sprite",
        rename_menu_item: " Rename Sprite",
        tree_root_item: "Sprites",
        image: IMAGE_REFS.sprite,
    },
    AssetDef {
        asset_type: DataAssetType::PalSprite,
        default_name_prefix: "pal_sprite",
        type_name: "Paletted Sprite",
        add_menu_item: " Add Paletted Sprite",
        duplicate_menu_item: " Duplicate Paletted Sprite",
        remove_menu_item: " Delete Paletted Sprite",
        rename_menu_item: " Rename Paletted Sprite",
        tree_root_item: "Paletted Sprites",
        image: IMAGE_REFS.pal_sprite,
    },
    AssetDef {
        asset_type: DataAssetType::SpriteAnimation,
        default_name_prefix: "animation",
        type_name: "Animation",
        add_menu_item: " Add Animation",
        duplicate_menu_item: " Duplicate Animation",
        remove_menu_item: " Delete Animation",
        rename_menu_item: " Rename Animation",
        tree_root_item: "Animations",
        image: IMAGE_REFS.animation,
    },
    AssetDef {
        asset_type: DataAssetType::Sfx,
        default_name_prefix: "sfx",
        type_name: "SFX",
        add_menu_item: " Add SFX",
        duplicate_menu_item: " Duplicate SFX",
        remove_menu_item: " Delete SFX",
        rename_menu_item: " Rename SFX",
        tree_root_item: "SFX",
        image: IMAGE_REFS.sfx,
    },
    AssetDef {
        asset_type: DataAssetType::ModData,
        default_name_prefix: "mod",
        type_name: "MOD",
        add_menu_item: " Add MOD",
        duplicate_menu_item: " Duplicate MOD",
        remove_menu_item: " Delete MOD",
        rename_menu_item: " Rename MOD",
        tree_root_item: "MODs",
        image: IMAGE_REFS.mod_data,
    },
    AssetDef {
        asset_type: DataAssetType::Font,
        default_name_prefix: "font",
        type_name: "Font",
        add_menu_item: " Add Font",
        duplicate_menu_item: " Duplicate Font",
        remove_menu_item: " Delete Font",
        rename_menu_item: " Rename Font",
        tree_root_item: "Fonts",
        image: IMAGE_REFS.font,
    },
    AssetDef {
        asset_type: DataAssetType::PropFont,
        default_name_prefix: "prop_font",
        type_name: "Prop Font",
        add_menu_item: " Add Prop Font",
        duplicate_menu_item: " Duplicate Prop Font",
        remove_menu_item: " Delete Prop Font",
        rename_menu_item: " Rename Prop Font",
        tree_root_item: "Prop Fonts",
        image: IMAGE_REFS.prop_font,
    },
];

pub fn get_asset_type_display_name(asset_type: DataAssetType) -> Option<&'static str> {
    ASSET_DEFS.iter().find(|def| def.asset_type == asset_type).map(|def| def.type_name)
}
