use crate::misc::IMAGE_REFS;
use crate::data_asset::DataAssetType;

pub struct AssetDef {
    pub id: &'static str,
    pub asset_type: DataAssetType,
    pub default_name_prefix: &'static str,
    pub add_menu_item: &'static str,
    pub remove_menu_item: &'static str,
    pub tree_root_item: &'static str,
    pub image: crate::misc::image_table::ImageRef,
}

pub const ASSET_DEFS : &[AssetDef] = &[
    AssetDef {
        id: "tileset_asset_def",
        asset_type: DataAssetType::Tileset,
        default_name_prefix: "tileset",
        add_menu_item: "Add Tileset",
        remove_menu_item: "Delete Tileset",
        tree_root_item: "Tilesets",
        image: IMAGE_REFS.tileset,
    },
    AssetDef {
        id: "map_asset_def",
        asset_type: DataAssetType::MapData,
        default_name_prefix: "map",
        add_menu_item: "Add Map",
        remove_menu_item: "Delete Map",
        tree_root_item: "Maps",
        image: IMAGE_REFS.map_data,
    },
    AssetDef {
        id: "room_asset_def",
        asset_type: DataAssetType::Room,
        default_name_prefix: "room",
        add_menu_item: "Add Room",
        remove_menu_item: "Delete Room",
        tree_root_item: "Rooms",
        image: IMAGE_REFS.room,
    },
    AssetDef {
        id: "sprite_asset_def",
        asset_type: DataAssetType::Sprite,
        default_name_prefix: "sprite",
        add_menu_item: "Add Sprite",
        remove_menu_item: "Delete Sprite",
        tree_root_item: "Sprites",
        image: IMAGE_REFS.sprite,
    },
    AssetDef {
        id: "animation_asset_def",
        asset_type: DataAssetType::SpriteAnimation,
        default_name_prefix: "animation",
        add_menu_item: "Add Animation",
        remove_menu_item: "Delete Animation",
        tree_root_item: "Animations",
        image: IMAGE_REFS.animation,
    },
    AssetDef {
        id: "sfx_asset_def",
        asset_type: DataAssetType::Sfx,
        default_name_prefix: "sfx",
        add_menu_item: "Add SFX",
        remove_menu_item: "Delete SFX",
        tree_root_item: "SFX",
        image: IMAGE_REFS.sfx,
    },
    AssetDef {
        id: "mod_asset_def",
        asset_type: DataAssetType::ModData,
        default_name_prefix: "mod",
        add_menu_item: "Add MOD",
        remove_menu_item: "Delete MOD",
        tree_root_item: "MODs",
        image: IMAGE_REFS.mod_data,
    },
    AssetDef {
        id: "font_asset_def",
        asset_type: DataAssetType::Font,
        default_name_prefix: "font",
        add_menu_item: "Add Font",
        remove_menu_item: "Delete Font",
        tree_root_item: "Fonts",
        image: IMAGE_REFS.font,
    },
    AssetDef {
        id: "prop_asset_def",
        asset_type: DataAssetType::PropFont,
        default_name_prefix: "prop_font",
        add_menu_item: "Add Prop Font",
        remove_menu_item: "Delete Prop Font",
        tree_root_item: "Prop Fonts",
        image: IMAGE_REFS.prop_font,
    },
];
